### ISSUE TITLE
List of pokemon attributes

### ISSUE THREAD

**Issue by riverajo** [nimbian/pokepong_webapp#8]
I need a list of pokemon atributes that are need to be stored and loaded to play the battle portion of the game.

**Comment by nimbian** [comment]
CREATE TABLE "ownedpkmn" (
    `owner` TEXT,
    `pokemon`   TEXT,
    `move1` TEXT,
    `move2` TEXT,
    `move3` TEXT,
    `move4` TEXT,
    `lvl`   INTEGER,
    `hpev`  INTEGER,
    `attackev`  INTEGER,
    `defenseev` INTEGER,
    `speedev`   INTEGER,
    `specialev` INTEGER,
    `attackiv`  INTEGER,
    `defesneiv` INTEGER,
    `speediv`   INTEGER,
    `specialiv` INTEGER,
    `exp`   INTEGER,
    `pp1`   INTEGER,
    `pp2`   INTEGER,
    `pp3`   INTEGER,
    `pp4`   INTEGER
);

**Comment by riverajo** [comment]
Completed.
